window.photoAlbums = [
  {
    slug: "new-york",
    title: "NEW YORK",
    cover: "photos/covers/new-york.jpg",
    photos: [],
  },
  {
    slug: "los-angeles",
    title: "LOS ANGELES",
    cover: "photos/covers/los-angeles.jpg",
    photos: [],
  },
  {
    slug: "san-francisco",
    title: "SAN FRANCISCO",
    cover: "photos/covers/san-francisco.jpg",
    photos: [],
  },
  {
    slug: "doha",
    title: "DOHA",
    cover: "photos/covers/doha.jpg",
    photos: [],
  },
  {
    slug: "paris",
    title: "PARIS",
    cover: "photos/covers/paris.jpg",
    photos: [],
  },
  {
    slug: "copenhagen",
    title: "COPENHAGEN",
    cover: "photos/covers/copenhagen.jpg",
    photos: [],
  },
  {
    slug: "malmo",
    title: "MALMO",
    cover: "photos/covers/malmo.jpg",
    photos: [],
  },
  {
    slug: "tromso",
    title: "TROMSO",
    cover: "photos/covers/tromso.jpg",
    photos: [],
  },
  {
    slug: "lisbon",
    title: "LISBON",
    cover: "photos/covers/lisbon.jpg",
    photos: [],
  },
  {
    slug: "barcelona",
    title: "BARCELONA",
    cover: "photos/covers/barcelona.jpg",
    photos: [],
  },
  {
    slug: "scottish-highlands",
    title: "SCOTTISH HIGHLANDS",
    cover: "photos/covers/scottish-highlands.jpg",
    photos: [],
  },
  {
    slug: "edinburgh",
    title: "EDINBURGH",
    cover: "photos/covers/edinburgh.jpg",
    photos: [],
  },
  {
    slug: "manchester",
    title: "MANCHESTER",
    cover: "photos/covers/manchester.jpg",
    photos: [],
  },
  {
    slug: "london",
    title: "LONDON",
    cover: "photos/covers/london.jpg",
    photos: [],
  },
  {
    slug: "bristol",
    title: "BRISTOL",
    cover: "photos/covers/bristol.jpg",
    photos: [],
  },
];
